sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=orda/iot-base
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
services:
  - docker
