version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy docker image
          command: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            REPO=orda/iot-base
            docker build -f Dockerfile -t $REPO:$CIRCLE_SHA1 .
            docker tag $REPO:$COMMIT $REPO:latest
            docker push $REPO
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
    filters:
      branches:
        only:
          - develop
